name: ✨ Feature Request
description: Suggest an idea for improvement or a new feature
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched the existing issues to make sure this feature hasn't been requested yet
          required: true
        - label: I have read the Contributing Guidelines
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see implemented
      placeholder: Describe the feature you want to be added...
    validations:
      required: true

  - type: textarea
    id: problem-usecase
    attributes:
      label: Problem / Use Case
      description: Explain the problem this feature solves or why it would be useful
      placeholder: What problem does this feature solve? Why would it be useful?
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - User interface improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you think this feature should work
      placeholder: How should this feature work? What should the user experience be like?

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or features you've considered
      placeholder: What alternatives have you considered? Why is this approach better?

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas about how to implement this feature, share them here
      placeholder: Any technical implementation suggestions or code snippets

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to work on this feature myself
        - label: I can provide additional clarification or testing
        - label: I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: Any additional information, mockups, or examples that would help understand the feature

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Provide examples of similar features in other projects or tools
      placeholder: Links to similar features in other projects, tools, or websites